### PR TITLE
Write the error output from Protobuf parse exceptions

### LINKED ISSUE #82: Improve ProtobufSrcGenExceptions to actually point where the errors are happening
Right now, we handle any issues with Protobuf source generation by wrapping the error in a ProtobufSrcGenException and raising it at runtime, specifically like this

```
final case class ProtobufSrcGenException(message: String) extends NoStackTrace

// ...

private def getCode[F[_]](
          file: File
      )(implicit F: Sync[F]): F[(String, ErrorsOr[List[String]])] =
        parseProto[F, Mu[ProtobufF]]
          .parse(ProtoSource(file.getName, file.getParent, Some(idlTargetDir.getCanonicalPath)))
          .flatMap { protocol =>
            val path = getPath(protocol)
            (transformToMuProtocol andThen generateScalaSource)(protocol) match {
              case Left(error) =>
                F.raiseError(
                  ProtobufSrcGenException(
                    s"Failed to generate Scala source from Protobuf file ${file.getAbsolutePath}. Error details: $error"
                  )
                )
              case Right(fileContent) =>
                F.pure(path -> Valid(splitLines(fileContent)))
            }
          }
```

While this _seems_ to make sense, in practice this approach ends up swallowing the errors in the exception and not surfacing them to the user.  For example, when I try and generate code from an invalid protobuf file in a separate project, this is the message I get:

```
$ muSrcGen
[error] stack trace is suppressed; run last protocol / muSrcGen for the full output
[error] (protocol / muSrcGen) higherkindness.mu.rpc.srcgen.proto.ProtoSrcGenerator$ProtobufSrcGenException
[error] Total time: 1 s, completed Aug 13, 2020, 10:49:20 AM
```

and then running `last protocol / muSrcGen` still doesn't give me any insightful output:

```
$ last protocol / muSrcGen
[error] higherkindness.mu.rpc.srcgen.proto.ProtoSrcGenerator$ProtobufSrcGenException
[error] (protocol / muSrcGen) higherkindness.mu.rpc.srcgen.proto.ProtoSrcGenerator$ProtobufSrcGenException
```

As a user, all this error tells me is that _something_ is wrong with my protobuf files, but it doesn't tell me which file or what specifically is wrong.  My theory is that this is being unintentionally caused by making the custom exception extend the `NoStackTrace` trait, but I'd have to dig a bit deeper to be sure.

My optimal behavior is that this error shows the user the path the to erroneous file and what the error specifically is.

### PR DESCRIPTION
**Pull request by dmarticus**
Closes #82.  Turns out we just needed to override the `toString` method when using our custom exception.

Old output:
```
$ muSrcGen
[error] stack trace is suppressed; run last protocol / muSrcGen for the full output
[error] (protocol / muSrcGen) higherkindness.mu.rpc.srcgen.proto.ProtoSrcGenerator$ProtobufSrcGenException
[error] Total time: 1 s, completed Aug 13, 2020, 10:49:20 AM
```

New output:
```
$ muSrcGen
[error] stack trace is suppressed; run last protocol / muSrcGen for the full output
[error] (protocol / muSrcGen) Failed to generate Scala source from Protobuf file /Users/dylan/Work/playground/test-protobuf-packages/protocol/target/scala-2.13/resource_managed/main/proto/proto/hello.proto. Error details: Failed to parse package name: <input>:1: error: illegal start of simple expression
[error]
[error] ^
[error] Total time: 1 s, completed Aug 13, 2020, 11:25:16 AM
```

### CODE REVIEW

File: core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroSrcGenTests.scala [hunk 1]
```diff
@@ -37,6 +43,25 @@ class AvroSrcGenTests extends AnyWordSpec with Matchers with OneInstancePerTest
...
+        ).generateFrom(
+          Source.fromInputStream(getClass.getResourceAsStream("/avro/Invalid.avdl")).mkString,
+          Avro
+        )
+      }
+
+      val expectedResponse =
+        "Some((foo/bar/MyGreeterService.scala,Invalid(NonEmptyList(RPC method response parameter has non-record response type 'STRING'))))"
+
+      assert(response.toString == expectedResponse)
```
Comment (fedefernandez) [inline core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroSrcGenTests.scala:63]: Would it be possible to check the type instead of the string representation?
```suggestion
      response shouldBe Some(("foo/bar/MyGreeterService.scala", Validated.invalidNel("RPC method response parameter has non-record response type 'STRING'")))
```

**Comment by dmarticus** [comment]
@fedefernandez your suggestions have been applied and CI passes, can I merge this PR?

**Review by fedefernandez — APPROVED** [review]
Looks good to me! Thanks
